apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
      name: auth
    spec:
      containers:
      - name: auth-container
        image: mousanageh/kub-auth:1
        imagePullPolicy: Always
